# Copyright (c) 2009 Symbian Foundation Ltd
# This component and the accompanying materials are made available
# under the terms of the License "Eclipse Public License v1.0"
# which accompanies this distribution, and is available
# at the URL "http://www.eclipse.org/legal/epl-v10.html".
#
# Initial Contributors:
# Symbian Foundation Ltd - initial contribution.
# Mike Kinghan, mikek@symbian.org
#
# Contributors:
#
# Description:
# This is a Linux makefile for the Symbian build tools components.

epocroot := $(dir $(realpath ../epoc32))
ifneq '$(epocroot)' ''
epocroot := $(patsubst %/,%,$(epocroot))
$(warning WARNING: EPOCROOT not set. Assuming $(epocroot))
export EPOCROOT=$(epocroot)
else
$(error EPOCROOT must be defined as the parent directory of your epoc32 tree)
endif

ifdef EPOCROOT
include $(EPOCROOT)/build/makefiles-garage/global-make-env.mk
endif

ifeq '$(file)' ''
file = diffs.patch
endif

garage = $(EPOCROOT)/build/makefiles-garage
garage_makefiles = $(shell find $(garage) -name Makefile)
targets = $(notdir $(patsubst %/Makefile,%,$(garage_makefiles)))
clean_targets = $(addsuffix -clean,$(targets))
what_targets = $(addsuffix -what,$(targets))
garage_make_dirs = $(patsubst %/Makefile,%,$(garage_makefiles))
make_dirs = $(patsubst $(garage)%,$(EPOCROOT)/build%,$(garage_make_dirs)) 
makefiles = $(patsubst $(garage)/%,$(EPOCROOT)/build/%,$(garage_makefiles))
raptor_linux_binaries = $(EPOCROOT)/build/sbsv2/raptor/linux-*
new_subdirs = $(EPOCROOT)/build/imgtools/romtools/r_t_areaset
subdirs = imgtools e32tools sbsv2 srctools buildframework buildtoolguides bintools
	
.PHONY: all tools export gen_preinclude clean distclean deploy_makefiles gather_makefiles help \
sbs_comp_list sbs_targ_list list_fixups list_prereqs


all: tools

tools: $(preinclude) $(makefiles)
	for dir in $(subdirs); do $(MAKE) -C $$dir; done

 
#export: tools
#	for dir in $(subdirs); do $(MAKE) -C $$dir export; done
		
clean: $(makefiles)
	for dir in $(subdirs); do $(MAKE) -C $$dir clean; done

distclean: clean
	rm -f -r $(makefiles) $($(preinclude) $(linux_gcc_defs_inc) $(raptor_linux_binaries) $(new_subdirs)

help:
	@echo "Build the Symbian build tools by conventional GNU/Linux means."
	@echo "PHONY targets:"
	@echo "" 	
	@echo "  help"
	@echo "  all              - Build all real targets (default)"
	@echo "  clean            - Remove all build object files, libraries and executables"
	@echo "  TARGET-clean     - clean the real target TARGET"
	@echo "  distclean        - Remove everything but the original files"
	@echo "  deploy_makefiles - Copy makefiles from the 'makefiles_garage' to the locations where they run"
	@echo "  gather_makefiles - Gather any new or updated makefiles from the places where they run into the 'makefiles_garage'"
	@echo "  export           - TODO: No exports are implemented yet"
	@echo "  what             - List the files built by the real targets."
	@echo "  missing          - List the real targets that do not exist."
	@echo "  TARGET-what      - List the files built by the real target TARGET." 
	@echo "  sbs_comp_list    - List the components that sbs would find (BLD.INF files)"
	@echo "  sbs_targ_list    - List the targets that sbs would find (MMP files)"
	@echo "  list_prereqs     - List the dependency graph of final targets"
	@echo "  list_fixes       - List the targets and files for which fixes are currently applied."
	@echo "                     The fixes are applied by the make and removed by clean."
	@echo "  fix              - Just apply the fixes. Don't build."
	@echo "  diff [file=FILE] - List the diffs that are generated by applying the fixups."
	@echo "                     The diffs are written to FILE, if specified, else to ./diffs.patch."
	@echo ""  
	@echo "Real targets in hierarchy:"
	@echo ""
	@for file in $(sort $(garage_makefiles)); do \
		dummy=`grep '^include $$(EPOCROOT)/build/makefiles-garage/todo.mk' $$file 2> /dev/null`;\
		todo=;\
		file=$${file#$(garage)/};\
		file=$${file%/Makefile};\
		targ=$${file##*/};\
		file=$${file%/*};\
		file=$${file%$${targ}};\
		file=`echo $$file | sed -e 's|/||g' -`;\
		file=$${file//?/-};\
		if [ "$${dummy}" != "" ]; then todo='  ### TODO ###'; fi; \
		echo "  $$file$$targ$$todo";\
	done

$(makefiles): $(EPOCROOT)/build/%: $(garage)/%
	mkdir -p $(dir $@) && cp $< $@

deploy_makefiles: $(makefiles)

gather_makefiles:
	for dir in $(subdirs); do \
		grep --include Makefile -r -e 'include $$(EPOCROOT)/build/makefiles-garage/global-make-env.mk' $$dir | \
		sed -e 's|:include $$(EPOCROOT)/build/makefiles-garage/global-make-env.mk||g' -e 's|$(EPOCROOT)/build/||g' - | while read makefile; do \
			if [ ! -f $(garage)/$$makefile ]; then \
				echo "### Garaging new makefile $(garage)/$$makefile ###" ;\
				cp -f --parents $$makefile $(garage); \
			else if [ $(EPOCROOT)/build/$$makefile -nt $(garage)/$$makefile ]; then \
				if [ "`diff $(EPOCROOT)/build/$$makefile $(garage)/$$makefile`" != "" ]; then \
					echo "### Updating garaged makefile $(garage)/$$makefile ###" ;\
					cp -f --parents $$makefile $(garage); \
				fi; \
			fi; \
			fi; \
		done; \
	done

sbs_comp_list:
	@for file in `find . -iname 'bld.inf'`; do echo $${file}; done

sbs_targ_list:
	@for file in `find . -iname '*.mmp'`; do echo $${file}; done

list_fixes: $(makefiles)
	@for make_dir in $(sort $(make_dirs)); do \
		$(MAKE) -s -C $$make_dir call_in=1 targ=$${make_dir##*/} _list_fixes; \
	done	

list_prereqs: $(makefiles)
	@for make_dir in $(sort $(make_dirs)); do \
		$(MAKE) -s -C $$make_dir call_in=1 targ=$${make_dir##*/} _list_prereqs; \
	done

fix: $(makefiles)
	@for make_dir in $(sort $(make_dirs)); do \
		$(MAKE) -C $$make_dir call_in=1 fixes; \
	done

what: $(makefiles)
	@for make_dir in $(sort $(make_dirs)); do \
		$(MAKE) -s -C $$make_dir call_in=1 targ=$${make_dir##*/} _what; \
	done

missing: $(makefiles) 
	@for make_dir in $(sort $(make_dirs)); do \
		$(MAKE) -s -C $$make_dir call_in=1 targ=$${make_dir##*/} _missing; \
	done

diff:
	$(MAKE) distclean && \
	rm -fr ../pristine && \
	mkdir ../pristine && \
	cp -r -t ../pristine * && \
	$(MAKE) fix && \
	diff -r -b ../pristine ../build > $(file)
	for file in `find bintools/rcomp -name '*.CPP.original' -or -name '*.H.original' -or -name '*.LEX.original' -or -name '*.YACC.original'`; do \
		lcfile=$$(file%\.original) && \
		lcfile=`echo $$lcile | tr '[:upper:]' '[:lower:]'` && \
		diff -r -b $$file $$lcfile >> $(file); \
	done   

$(targets): $(preinclude) $(makefiles)
	garage_makedir=`find $(garage) -name $@`;\
	makedir=$${garage_makedir##$(garage)/};\
	makedir=$(EPOCROOT)/build/$${makedir};\
	$(MAKE) -C $${makedir}

$(clean_targets): $(makefiles)
	targ=$@; \
	targ=$${targ%-clean}; \
	garage_makedir=`find $(garage) -name $${targ}`;\
	if [ "$$garage_makedir" != "" ]; then \
		makedir=$${garage_makedir##$(garage)/};\
		makedir=$(EPOCROOT)/build/$${makedir};\
		$(MAKE) -C $${makedir} clean; \
	fi


$(what_targets): $(makefiles)
	@targ=$@; \
	targ=$${targ%-what}; \
	garage_makedir=`find $(garage) -name $${targ}`;\
	if [ "$$garage_makedir" != "" ]; then \
		makedir=$${garage_makedir##$(garage)/};\
		makedir=$(EPOCROOT)/build/$${makedir};\
		$(MAKE) -C $${makedir} call_in=1 targ=$${make_dir##*/} what; \
	fi

